# Generated by Django 3.1.3 on 2021-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='banner',
            field=models.BooleanField(default=False),
        ),
    ]
