# Generated by Django 3.1.3 on 2021-02-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_song_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='category_image',
            new_name='album_image',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='category_name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='category',
            new_name='Album',
        ),
    ]
