# Generated by Django 3.1.3 on 2021-02-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210213_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, default='', upload_to='album-images/'),
        ),
    ]
