# Generated by Django 3.1.3 on 2021-02-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210213_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Album',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.artist'),
        ),
    ]
