# Generated by Django 3.1.3 on 2021-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210226_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default=None, upload_to='songs/'),
        ),
    ]
